INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303001101',true,'יונקים');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303001101',false,'זוחלים');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303001101',false,'דו חיים');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303001101',false,'עופות');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303001102',true,'זאב');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303001102',false,'שועל');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303001102',false,'תן');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303001102',false,'פנק');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303001103',true,'מיקום של פרחים נושאי צוף');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303001103',false,'היכן מסתתרים טורפים');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303001103',false,'עם איזה דבור ברצונן להתחתן');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303001103',false,'מהו תאריך יום ההולדת שלהן');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303001104',true,'תוכי');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303001104',false,'פלמינגו');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303001104',false,'סנונית');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303001104',false,'עיט');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303001105',true,'חטים');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303001105',false,'פיגיון');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303001105',false,'שפיצונים');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303001105',false,'רומחים');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303002101',true,'אייל נקוד');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303002101',false,'בואש');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303002101',false,'לוטרה');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303002101',false,'לייש');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303002102',true,'שועל');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303002102',false,'זברה');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303002102',false,'צפרדע');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303002102',false,'דישון');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303002103',true,'האריה');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303002103',false,'הדוב');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303002103',false,'הנמר');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303002103',false,'הזאב');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303002104',true,'ינשוף');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303002104',false,'יען');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303002104',false,'הדרור');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303002104',false,'אלבטרוס');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303002105',true,'סנאי');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303002105',false,'ארנב');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303002105',false,'זברה');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303002105',false,'דוב');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303003101',true,'השמש');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303003101',false,'פרוקסימה קנטאורי');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303003101',false,'סיריוס');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303003101',false,'פולאריס');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303003102',true,'יותר מ-70');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303003102',false,'בדיוק 9');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303003102',false,'לכול היותר 23');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303003102',false,'פחות מ-19');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303003103',true,'כוכב חמה');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303003103',false,'נוגה');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303003103',false,'כדור הארץ');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303003103',false,'מאדים');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303003104',true,' שבתאי');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303003104',false,'מאדים');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303003104',false,' אורנוס');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303003104',false,' נפטון');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303003105',true,'אפולו 11');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303003105',false,'ספוטניק');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303003105',false,'וויאג`ר');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303003105',false,'ניו הורייזונס');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303004101',true,'סוכות');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303004101',false,'פסח');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303004101',false,'שבועות');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303004101',false,'פורים');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303004102',true,'סופגניות');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303004102',false,'סושי');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303004102',false,'בורקס פטריות');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303004102',false,'מצות');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303004103',true,'פורים');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303004103',false,'יום העצמאות');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303004103',false,'ט"ו בשבט');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303004103',false,'יום הזיכרון');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303004104',true,'פסח');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303004104',false,'ראש השנה');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303004104',false,'חנוכה');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303004104',false,'סוכות');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303004105',true,'ט"ו בשבט');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303004105',false,'פסח');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303004105',false,'יום העצמאות');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303004105',false,'סוכות');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303005101',true,'שורש');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303005101',false,'עלה');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303005101',false,'פרח');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303005101',false,'גבעול');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303005102',true,'ירוק');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303005102',false,'כחול');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303005102',false,'צהוב');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303005102',false,'טורקיז');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303005103',true,'עלי כותרת');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303005103',false,'עלי כינור');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303005103',false,'עלי נבל');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303005103',false,'עלי בריקדות');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303005104',true,'העלה');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303005104',false,'גזע העץ');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303005104',false,'השורש');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303005104',false,'הגבעול');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303005105',true,'חלמונית');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303005105',false,'קלפתית');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303005105',false,'חלבונצ`יק');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303005105',false,'אפרוחון');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303006101',true,'ארגנטינוזאורוס');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303006101',false,'פרוטוצרטופס');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303006101',false,'סטירקוזאורוס');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303006101',false,'ולוצירפטור');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303006102',true,'בתקופת המזוזואיקון');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303006102',false,'תקופת הקרח');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303006102',false,'תקופת האבן');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303006102',false,'תקופת הצנע');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303006103',true,'הוולוצירפטור');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303006103',false,'הברכיוזאורוס');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303006103',false,'הטריצרטופס');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303006103',false,'הטירנוזאורוס');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303006104',true,'הטירנוזאורוס רקס');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303006104',false,'הברכיוזאורוס');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303006104',false,'הסטגוזאורוס');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303006104',false,'הדיפלודוקוס');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303006105',true,'הטריצרטופס');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303006105',false,'הוולוצירפטור');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303006105',false,'הטירנוזאורוס');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303006105',false,'גיגאנוטוזאורוס');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303007101',true,'כבשה');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303007101',false,'מחוגה');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303007101',false,'ילד אוכל גלידה');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303007101',false,'כתר');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303007102',true,'סוחר במכוניות גנובות');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303007102',false,'רופא עור');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303007102',false,'מוכר חמוצים');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303007102',false,'רופא שיניים');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303007103',true,'טיגר');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303007103',false,'קפטן קוק');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303007103',false,'הארי פוטר');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303007103',false,'פיטר פן');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303007104',true,'הרמיוני');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303007104',false,'אוויטה');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303007104',false,'בילבי בת גרב');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303007104',false,'בלבי בת כובע גרב');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303007105',true,'אליס בארץ הפלאות');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303007105',false,'צ`רלי ומפעל השוקולד');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303007105',false,'הנסיך הקטן');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303007105',false,'הארי פוטר');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303008101',true,'מים');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303008101',false,'כספית');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303008101',false,'נפט');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303008101',false,'שמן זית');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303008102',true,'חמצן');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303008102',false,'פחמן דו-חמצני');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303008102',false,'הליום');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303008102',false,'מתאן');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303008103',true,'עלי במבוק');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303008103',false,'ספגטי');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303008103',false,'עלי דקל');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303008103',false,'שוקולד מריר');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303008104',true,'קשת בענן');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303008104',false,'טורנדו');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303008104',false,'ברק');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303008104',false,'שלג');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303008105',true,'שלכת');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303008105',false,'נדידה');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303008105',false,'רחצה');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303008105',false,'שאיבה');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303009101',true,'פחמימות');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303009101',false,'חלבונים');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303009101',false,'שומנים');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303009101',false,'ויטמינים');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303009102',true,'תרד');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303009102',false,'גזר');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303009102',false,'בצל');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303009102',false,'עגבניות');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303009103',true,'תפוז');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303009103',false,'פופקורן');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303009103',false,'גבינה צהובה');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303009103',false,'ענבים');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303009104',true,'חלבונים');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303009104',false,'פחמימות');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303009104',false,'שומנים');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303009104',false,'סוכרים');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303009105',true,'ברוקולי');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303009105',false,'גמבה');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303009105',false,'תפוח אדמה');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303009105',false,'קישוא');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303010101',true,'כוח העילוי');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303010101',false,'כוח צנטריפוגלי');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303010101',false,'כוח דלתא');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303010101',false,'כוח המשיכה');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303010102',true,'צוללת');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303010102',false,'מונית');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303010102',false,'אופניים');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303010102',false,'טרקטורון');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303010103',true,'רכבת');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303010103',false,'אוטובוס');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303010103',false,'משאית');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303010103',false,'מכונית');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303010104',true,'מטוסי סילון');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303010104',false,'אופנוע ים');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303010104',false,'ג`יפ שטח ');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303010104',false,'ספינת משא');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303010105',true,'סירות מפרש');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303010105',false,'ג`יפ');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303010105',false,'מונית');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303010105',false,'אופנוע');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303011101',true,'האוקיינוס השקט');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303011101',false,'האוקיינוס האטלנטי');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303011101',false,'האוקיינוס ההודי');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303011101',false,'האוקיינוס הרועש');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303011102',true,'נהרות');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303011102',false,'ברזיות ציבוריות');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303011102',false,'בריכות שחייה');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303011102',false,'אגמים');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303011103',true,'במדבריות');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303011103',false,'בג`ונגלים');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303011103',false,'מעל האוקיינוס ההודי');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303011103',false,'בצפון אירופה');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303011104',true,'ים המלח');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303011104',false,'הים האדום');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303011104',false,'הים התיכון');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303011104',false,'האוקיינוס האטלנטי');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303011105',true,'אידוי');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303011105',false,'גשם');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303011105',false,'סערה');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303011105',false,'שלג');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303012101',true,'הריאות');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303012101',false,'הכבד');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303012101',false,'המרפק');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303012101',false,'תנוך האוזן');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303012102',true,'לתמוך בגוף ולהגן על איברים פנימיים');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303012102',false,'לשמור על טמפרטורת הגוף');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303012102',false,'לעכל מזון');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303012102',false,'להוביל דם');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303012103',true,'סוגי דם');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303012103',false,'סוגי טלפונים');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303012103',false,'מידות זנב של כלבים');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303012103',false,'אזורי חיוג');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303012104',true,'הכבד');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303012104',false,'הלב');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303012104',false,'המוח');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303012104',false,'הגרוגרת');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303012105',true,'לשלוט בתנועות הגוף ובחשיבה');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303012105',false,'להוביל דם');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303012105',false,'לעכל מזון');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303012105',false,'לייצר אנרגיה');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303013101',true,'עצם הסטייפס (באוזן)');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303013101',false,'עצם הירך');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303013101',false,'עצם הזרוע');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303013101',false,'עצם האצבע');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303013102',true,'יותר מ-200');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303013102',false,'191');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303013102',false,'613');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303013102',false,'177');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303013103',true,'עצמות הגולגולת');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303013103',false,'עצמות הגפיים');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303013103',false,'עצמות הצוואר');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303013103',false,'עצמות האגן');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303013104',true,'עצמות הלסת');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303013104',false,'חוט השדרה');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303013104',false,'עצם הזנב');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303013104',false,'ברך ימין');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303013105',true,'סידן');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303013105',false,'אורניום');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303013105',false,'יוד');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303013105',false,'ויטמין D');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303014101',true,'צייר');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303014101',false,'מוזיקאי');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303014101',false,'סופר');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303014101',false,'מדען');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303014102',true,'יצירת אמנות תלת-ממדית');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303014102',false,'ציור על קיר');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303014102',false,'ספר עם תמונות');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303014102',false,'שיר');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303014103',true,'סגול');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303014103',false,'ירוק');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303014103',false,'כתום');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303014103',false,'ורוד');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303014104',true,'שמן על קנבס');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303014104',false,'מים על נייר');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303014104',false,'פחם על נייר');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303014104',false,'דיו על קנבס');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303014105',true,'מקום לתצוגת יצירות אמנות');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303014105',false,'בית ספר');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303014105',false,'ספרייה');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303014105',false,'פארק');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303015101',true,'סין');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303015101',false,'צרפת');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303015101',false,'ארצות הברית');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303015101',false,'ברזיל');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303015102',true,'ספרדית');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303015102',false,'אנגלית');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303015102',false,'פורטוגזית');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303015102',false,'צרפתית');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303015103',true,'ברזיל');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303015103',false,'יפן');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303015103',false,'אוסטרליה');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303015103',false,'רוסיה');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303015104',true,'הודו');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303015104',false,'איטליה');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303015104',false,'יוון');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303015104',false,'מצרים');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303015105',true,'יפן');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303015105',false,'גרמניה');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303015105',false,'קנדה');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303015105',false,'אתיופיה');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303016101',true,'אנטואן דה סן-אכזופרי');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303016101',false,'ג`יי.קיי. רולינג');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303016101',false,'רואלד דאל');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303016101',false,'לואיס קרול');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303016102',true,'האחים גרים');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303016102',false,'האחים רייט');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303016102',false,'האחים קרמזוב');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303016102',false,'האחים מרקס');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303016103',true,'פינוקיו');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303016103',false,'הכלב היהודי');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303016103',false,'פיטר פן');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303016103',false,'הנסיך הקטן');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303016104',true,'סוס');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303016104',false,'סוס ים');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303016104',false,'פרת משה רבינו');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303016104',false,'כריש פטיש');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303016105',true,'"היפיפיה הנרדמת"');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303016105',false,'"הצפרדע המלך"');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303016105',false,'"סינדרלה"');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303016105',false,'"האחיות הרעות"');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303017101',true,'אסיה');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303017101',false,'אפריקה');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303017101',false,'אירופה');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303017101',false,'אוסטרליה');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303017102',true,'האוקיינוס השקט');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303017102',false,'האוקיינוס האטלנטי');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303017102',false,'האוקיינוס ההודי');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303017102',false,'האוקיינוס הארקטי');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303017103',true,'0 מעלות');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303017103',false,'23.5 מעלות צפון');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303017103',false,'45 מעלות צפון');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303017103',false,'90 מעלות צפון');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303017104',true,'האוורסט');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303017104',false,'הקילימנג`רו');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303017104',false,' מונבלאן');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303017104',false,'הר מירון');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303017105',true,'רוסיה');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303017105',false,'סין');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303017105',false,'ארצות הברית');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303017105',false,'ברזיל');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303018101',true,'הטיגריס הסיבירי');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303018101',false,'הפיל האפריקאי');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303018101',false,'עורב');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303018101',false,'הדולפין');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303018102',true,'קרנף ');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303018102',false,'תמסח');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303018102',false,'לביא');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303018102',false,'דביבון');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303018103',true,'זברה ');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303018103',false,'דב נמלים');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303018103',false,'ברדלס');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303018103',false,'דישון');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303018104',true,'בתוך דג גדול');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303018104',false,'בשק שינה');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303018104',false,'בחבית בירה');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303018104',false,'בספריה הלאומית');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303018105',true,'מיינה');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303018105',false,'נשר');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303018105',false,'בז');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303018105',false,'עיט');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303019101',true,'יהלום');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303019101',false,'דבש');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303019101',false,'מיונז');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303019101',false,'אורניום');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303019102',true,'ברקת');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303019102',false,'אודם');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303019102',false,'יהלום');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303019102',false,'גרניט');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303019103',true,'סלע משקע');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303019103',false,'סלע שמקורו בפעילות געשית');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303019103',false,'סלע המאופיין בקושי רב');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303019103',false,'עשוי מקמח');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303019104',true,'כחול');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303019104',false,'ורוד');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303019104',false,'בז`');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303019104',false,'סגול');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303019105',true,'קוורץ');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303019105',false,'ענבר');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303019105',false,'גרנט');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303019105',false,'קריסטל');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303020101',true,'כליות');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303020101',false,'מפרקים');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303020101',false,'שרירים');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303020101',false,'לב');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303020102',true,'דב נמלים');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303020102',false,'תן');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303020102',false,'גרביל');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303020102',false,'שפיפון');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303020103',true,'מורה');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303020103',false,'רופא');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303020103',false,'עורך דין');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303020103',false,'קונדיטור');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303020104',true,'סופר');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303020104',false,'צייר');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303020104',false,'מדריך טיולים');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303020104',false,'שף');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303020105',true,'אדריכלות');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303020105',false,'רוקחות');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303020105',false,'נדל"ן');
INSERT INTO answer_options (question_id, correct_answer, answer_text) VALUES ('303020105',false,'מדעי הבטון והמלט');
